swagger: '2.0'

info:
  title: API Repository API
  version: '0.2'
  description: |
    Storage API of the API Discovery Solution (a.k.a Meta-API) is currently used to manage versions and Applications of
    APIs. Later, it will be also used to manage API's meta information like documentation and user manuals.

    API resource represents an abstract API. One particular API has one or more Versions which can be deployed in
    multiple Applications. An Application can implement multiple APIs.

    APIs, Applications, and Versions have defined lifecycles. An Application is ACTIVE if it has been crawled recently.
    An Application gets INACTIVE or DECOMMISSIONED if it wasn't available for a long period of time. The Application
    lifecycle state gets lifted to the lifecycle state of the API Version: a Version is ACTIVE if there is an ACTIVE
    Application which implements the given Version of the API. API lifecycle aggregates the lifecycle statuses of its
    Versions: an API is ACTIVE if there is at least one ACTIVE Version.

externalDocs:
  description: API Repository Solution Documentation
  url: https://github.com/zalando-incubator/api-discovery

basePath: /
produces:
- application/json
consumes:
- application/json

security:
- oauth2: [uid, api-is.api-repository.api-definition.write]

paths:
  '/apis':
    get:
      summary: list all APIs
      description: Lists of all APIs
      operationId: 'org.zalando.apidiscovery.storage.api/read-apis'
      tags:
      - APIs
      security:
      - oauth2:
        - uid
      parameters:
      - name: lifecycle_state
        in: query
        type: string
        description: Filter APIs by lifecycle state
        required: false
      responses:
        200:
          description: List of APIs
          schema:
            type: array
            items:
              $ref: '#/definitions/APIMetadata'
        default:
          $ref: '#/responses/Error'

  '/apis/{api_id}':
    get:
      summary: read API
      description: Returns details about the API
      operationId: 'org.zalando.apidiscovery.storage.api/read-api'
      tags:
      - APIs
      security:
      - oauth2:
        - uid
      parameters:
      - name: api_id
        in: path
        type: string
        description: ID of the API
        required: true
      responses:
        200:
          description: API's details
          schema:
            $ref: '#/definitions/API'
        default:
          $ref: '#/responses/Error'

  '/apis/{api_id}/versions':
    get:
      summary: reads all versions of an API
      description: List of all versions of an API
      operationId: "org.zalando.apidiscovery.storage.api/get-api-versions!"
      tags:
      - APIs
      - Versions
      security:
      - oauth2:
        - uid
      parameters:
      - name: api_id
        in: path
        type: string
        description: ID of the API
        required: true
      - name: lifecycle_state
        in: query
        type: string
        description: Filter versions by lifecycle state
        required: false
      responses:
        200:
          description: List of API's versions
          schema:
            type: array
            items:
              $ref: '#/definitions/Version'
        default:
          $ref: '#/responses/Error'

  '/apis/{api_id}/versions/{version_id}':
    get:
      summary: reads a version of an API
      description: Specific version of an API
      operationId: "org.zalando.apidiscovery.storage.api/get-api-version!"
      tags:
      - APIs
      - Versions
      security:
      - oauth2:
        - uid
      parameters:
      - name: api_id
        in: path
        type: string
        description: ID of the API
        required: true
      - name: version_id
        in: path
        type: string
        description: Version ID
        required: true
      responses:
        200:
          description: Version of the API
          schema:
            $ref: '#/definitions/Version'
        default:
          $ref: '#/responses/Error'

  '/apis/{api_id}/versions/{version_id}/definition':
    get:
      summary: reads a definition of an API versions
      description: Definition of an API versions
      operationId: "org.zalando.apidiscovery.storage.api/get-api-version-definition!"
      tags:
      - APIs
      - Versions
      - Definitions
      security:
      - oauth2:
        - uid
      parameters:
      - name: api_id
        in: path
        type: string
        description: ID of the API
        required: true
      - name: version_id
        in: path
        type: string
        description: Version ID
        required: true
      responses:
        200:
          description: Swagger Definition of the API
          schema:
            $ref: '#/definitions/SwaggerDefinition'
        default:
          $ref: '#/responses/Error'

  '/apis/{api_id}/applications':
    get:
      summary: reads all Applications of an API
      description: List of all Applications of an API
      operationId: "org.zalando.apidiscovery.storage.api/get-api-applications!"
      tags:
      - APIs
      - Applications
      security:
      - oauth2:
        - uid
      parameters:
      - name: api_id
        in: path
        type: string
        description: ID of the API
        required: true
      - name: lifecycle_state
        in: query
        type: string
        description: Filter Applications by lifecycle state
        required: false
      responses:
        200:
          description: List of API's Applications
          schema:
            type: array
            items:
              $ref: '#/definitions/Application'
        default:
          $ref: '#/responses/Error'

  '/apis/{api_id}/applications/{application_name}':
    get:
      summary: reads a Application of an API
      description: Specific Application of an API
      operationId: "org.zalando.apidiscovery.storage.api/get-api-application!"
      tags:
      - APIs
      - Applications
      security:
      - oauth2:
        - uid
      parameters:
      - name: api_id
        in: path
        type: string
        description: ID of the API
        required: true
      - name: application_name
        in: path
        type: string
        description: application name
        required: true
      responses:
        200:
          description: Application of the API
          schema:
            $ref: '#/definitions/Application'
        default:
          $ref: '#/responses/Error'

  '/api-definitions/{api_definition_id}':
    put:
      summary: creates an API definition
      description: Creates an API definition
      operationId: "org.zalando.apidiscovery.storage.api/create-api-definition!"
      tags:
      - Definitions
      security:
      - oauth2:
        - uid
        - api-is.api-repository.api-definition.write
      parameters:
      - name: api_definition_id
        in: path
        type: string
        description: ID of the API, generated by client
        required: true
      - name: APIDefinition
        in: body
        description: API definition details that will be saved
        schema:
          $ref: '#/definitions/APIDefinition'
        required: true
      responses:
        201:
          description: API has been saved
        default:
          $ref: '#/responses/Error'

responses:
  Error:
    description: The occured error
    schema:
      $ref: '#/definitions/Error'

definitions:
  APIDefinition:
    type: object
    properties:
      status:
        type: string
        x-extensible-enum: [SUCCESSFUL, UNSUCCESSFUL]
        description: The current status of the crawling
        example: SUCCESSFUL
      type:
        type: string
        description: Type of API definition
        example: SWAGGER-2.0
      name:
        type: string
        description: Name of the API
        example: Kio API
      version:
        type: string
        description: Version of the API
        example: "1.0"
      service_url:
        type: string
        description: URL pointing to the Application which is providing the API
        example: https://kio.example.com
      url:
        type: string
        description: Path to the API definition file
        example: /swagger/api.json
      ui:
        type: string
        description: Path to the UI for browsing the API
        example: /swagger-ui
      definition:
        type: string
        description: The API definition
        example: |
          {"swagger": "2.0"
           "foo": "bar"}
    required:
    - status

  API:
    description: A representation of an abstract API
    allOf:
    - $ref: '#/definitions/APIMetadata'
    - type: object
      properties:
        applications:
          type: array
          items:
            $ref: '#/definitions/Application'
        versions:
          type: array
          items:
            $ref: '#/definitions/Version'

  APIMetadata:
    type: object
    properties:
      name:
        type: string
        description: Human readable name of the API
        example: API Discovery Storage API
      lifecycle_state:
        $ref: '#/definitions/LifecycleState'

  Application:
    type: object
    description: A deployed instance of the API
    properties:
      name:
        type: string
        description: Application name (e.g. application and/or environment name)
        example: sales-orders-app
      service_url:
        type: string
        description: URL of the Application
        example: sales-orders.api.zalando.com
      ui:
        type: string
        description: Path to the UI for browsing the API
        example: /swagger-ui
      url:
        type: string
        description: Path to the API definition
        example: /swagger/api.json
      lifecycle_state:
        $ref: '#/definitions/LifecycleState'
      versions:
        type: array
        items:
          $ref: '#/definitions/VersionLink'

  Version:
    type: object
    description: A version of one particular API
    properties:
      id:
        type: string
        description: opaque id of the version
        example: 123e4567-e89b-12d3-a456-426655440000
      swagger_version:
        type: string
        description: Version from the Swagger definition
        example: 1.0.0
      last_crawled:
        type: integer
        description: Last time crawled
        example: 1489072334
      type:
        type: string
        description: Type of the API definition
        example: swagger-2.0
      definition:
        type: string
        description: Formal definition of the API
        example: |
          {"swagger": "2.0"
           "foo": "bar"}
      lifecycle_state:
        $ref: '#/definitions/LifecycleState'
      applications:
        type: array
        items:
          $ref: '#/definitions/ApplicationLink'

  LifecycleState:
    type: string
    x-extensible-enum:
    - ACTIVE
    - INACTIVE
    - DECOMMISSIONED

  SwaggerDefinition:
    type: object
    description: Swagger definition in JSON format

  VersionLink:
    type: object
    properties:
      version_id:
        type: string
        example: 123e4567-e89b-12d3-a456-426655440000
        description: opaque id of the version
      created:
        type: integer
        description: first time crawled
        example: 1489072334
      last_crawled:
        type: integer
        description: last time crawled
        example: 1489072334
      lifecycle_state:
        $ref: '#/definitions/LifecycleState'
      href:
        type: string
        format: uri
        example: https://meta.api.example.com/apis/sales-orders/versions/123e4567-e89b-12d3-a456-426655440000
    required:
    - version_id
    - href

  ApplicationLink:
    type: object
    properties:
      application_name:
        type: string
        example: kio-app
        description: unique application name
      created:
        type: integer
        description: first time crawled
        example: 1489072334
      last_crawled:
        type: integer
        description: last time crawled
        example: 1489072334
      lifecycle_state:
        $ref: '#/definitions/LifecycleState'
      href:
        type: string
        format: uri
        example: https://meta.api.example.com/apis/sales-orders/applicatons/kio-app
    required:
    - application_name
    - href

  Error:
    type: object
    properties:
      message:
        type: string
        description: Human readable error message

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
      api-is.api-repository.api-definition.write: Scope allowing the user to write API definitions.