parser: babel-eslint

plugins:
  - babel
  - promise
  - react
  - prettier

extends:
  - eslint:recommended
  - plugin:react/recommended

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: false

parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true

env:
  es6: true
  browser: true
  commonjs: true

# http://eslint.org/docs/rules
rules:
  # Promise
  promise/always-return: 2
  promise/no-return-wrap: 2
  promise/param-names: 2
  promise/catch-or-return: 2
  promise/no-native: 0
  promise/no-nesting: 1
  promise/no-promise-in-callback: 1
  promise/no-callback-in-promise: 1
  promise/avoid-new: 0

  # Babel
  babel/new-cap: 1
  babel/object-curly-spacing: 0
  babel/no-invalid-this: 1
  babel/semi: 1

  # Prettier
  prettier/prettier:
    - 2
    - printWidth: 100
      singleQuote: true
